version: '4.31.1'
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dt_db
      POSTGRES_USER: dt_user
      POSTGRES_PASSWORD: dt_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3001:3001'
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      DATABASE_USER: dt_user
      DATABASE_PASSWORD: dt_password
      DATABASE_NAME: dt_db
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
